# Generated by Django 4.0.6 on 2022-08-01 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default='Sample todo', max_length=255)),
                ('completed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='sticker',
            name='completed',
        ),
        migrations.AlterField(
            model_name='sticker',
            name='text',
            field=models.CharField(default='Sample sticker', max_length=255),
        ),
        migrations.AlterField(
            model_name='table',
            name='stickers',
            field=models.ManyToManyField(null=True, to='stickers.sticker'),
        ),
        migrations.AddField(
            model_name='sticker',
            name='todos',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='stickers.todo'),
        ),
    ]
