# Generated by Django 4.0.6 on 2022-08-01 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0002_todo_remove_sticker_completed_alter_sticker_text_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='stickers',
            field=models.ManyToManyField(blank=True, to='stickers.sticker'),
        ),
    ]
