# Generated by Django 4.0.6 on 2022-08-01 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0006_alter_sticker_todos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker',
            name='todos',
        ),
        migrations.AddField(
            model_name='todo',
            name='sticker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='stickers.sticker'),
        ),
    ]
