# Generated by Django 4.0.6 on 2022-08-01 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0007_remove_sticker_todos_todo_sticker'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='sticker',
        ),
        migrations.AddField(
            model_name='sticker',
            name='todos',
            field=models.ManyToManyField(blank=True, to='stickers.todo'),
        ),
    ]
