# Generated by Django 4.0.6 on 2022-08-09 11:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0008_remove_todo_sticker_sticker_todos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sticker',
            name='todos',
        ),
        migrations.RemoveField(
            model_name='table',
            name='stickers',
        ),
        migrations.AddField(
            model_name='sticker',
            name='table',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='stickers.table'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='todo',
            name='sticker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='todos', to='stickers.sticker'),
        ),
        migrations.AlterField(
            model_name='sticker',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
