# Generated by Django 4.0.6 on 2022-08-09 15:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stickers', '0009_remove_sticker_todos_remove_table_stickers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sticker',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stickers', to='stickers.table'),
        ),
        migrations.RemoveField(
            model_name='table',
            name='user',
        ),
        migrations.AddField(
            model_name='table',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
