# Generated by Django 4.0.6 on 2022-08-01 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stickers', '0004_alter_sticker_todos'),
    ]

    operations = [
        migrations.AddField(
            model_name='sticker',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
